### PR TITLE
Add improvements to Docker containerization.

### PR DESCRIPTION
**Pull request by LeeBergstrand**
Hi,

I was just using the docker containers from my fork and noticed a few small bugs. I have addressed these issues. 

- Changed Dockerfile headings and documentation to make them more generic for merging into mainline genome properties.
- Added some changes to the shell script for assigning genome properties using a docker container.
  - The script can now be run anywhere in the system rather than just the repository directory.
  - The file name of genome properties assignment files has been shortened and is no longer overly verbose.

Cheers,

Lee

### CODE REVIEW

**Comment by LeeBergstrand** [comment]
@rdfinn I missed a few things with the docker containers. My apologies.

**Comment by LeeBergstrand** [comment]
@happy-lorna @rdfinn Any updates with regards to this pull request?

**Comment by LornaMGnify** [comment]
Hi Lee, sorry for being slow to respond - I hadn't noticed there was an outstanding pull request (its a very busy time just now). @rdfinn will look at this as soon as possible.

**Comment by LeeBergstrand** [comment]
@happy-lorna Great thanks!

**Comment by rdfinn** [comment]
Thanks for the update, sorry it has taken me a few days to get to this.

**Pull request merged**
